services:
  - type: web
    name: monty-finance
    env: go
    region: frankfurt
    build:
      command: go build -o monty
    start:
      command: ./monty
    envVars:
      - key: DB_USER
        fromDatabase:
          name: monty-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: monty-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: monty-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: monty-db
          property: database
      - key: DB_PORT
        value: "5432"

databases:
  - name: monty-db
    databaseName: finance_db_r0mf
    user: finance_user
    region: frankfurt
    plan: free
    version: 16