services:
  - type: web
    name: monty-finance
    env: go
    region: frankfurt
    build:
      command: go build -o monty
    start:
      command: ./monty
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: monty-db
          property: connectionString

databases:
  - name: monty-db
    databaseName: finance_db
    user: finance_user
    region: frankfurt
    plan: free
    version: 16